# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('regdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('adddate', models.DateTimeField(null=True)),
                ('all_wishmaker', models.ManyToManyField(related_name='attending_wish', to='belt.User')),
                ('wish_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wish', to='belt.User')),
            ],
        ),
    ]
